# Generated by Django 2.2.18 on 2021-02-02 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0002_remove_curso_nombre_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='autores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='sobre_curso',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
